### ISSUE TITLE
Re scrapping issues

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#142]
I have my files named <releasedate> - <title> when re scrapping it will try using the date as the <ID> number. Even with append ID to start of title field when scrapping.

Also is there an easy way to batch re scrap sub folders? Say clicking the main folder then it grabs all the scenes from the sub folders.

**Comment by DoctorD1501** [comment]
The way the scraper currently work, it uses the last word of the filename (or the first word if the "Use First Word of File Instead of Last Word" for the ID. It doesn't use the title or any of the scraped data at all.

So just make sure when you are saving out the data, you keep the ID at the end of file name in the renamer settings.

I'll note that this is all probably an area of the program that could be improved. Another user had suggested allowing for a regular expression type thing which lets you specify how your files are named, for example.

**Comment by mjsmjs** [comment]
I'm now having a problem where when I go back to rescrap. It won't load any info. Or seem to select the file.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at moviescraper.doctord.model.dataitem.Thumb.<init>(Thumb.java:269)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlActorBean.toActor(KodiXmlActorBean.java:42)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlMovieBean.toMovie(KodiXmlMovieBean.java:147)
	at moviescraper.doctord.controller.SelectFileListAction.readMovieFromNfoFile(SelectFileListAction.java:165)
	at moviescraper.doctord.controller.SelectFileListAction.handleNewSelection(SelectFileListAction.java:104)
	at moviescraper.doctord.controller.SelectFileListAction.valueChanged(SelectFileListAction.java:46)
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.JList.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DoctorD1501** [comment]
Can you post the nfo of the file that you are loading?

**Comment by Wizell** [comment]
This is fixed in #201
