### ISSUE TITLE
Add support for HTTPS urls

### ISSUE THREAD

**Issue by MrTimscampi** [DoctorD1501/JAVMovieScraper#152]
I'm writing an EIC-Book scraper and found an issue where, trying to download images from an HTTPS link returns this:

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
    at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
    at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
    at sun.security.ssl.Handshaker.processLoop(Unknown Source)
    at sun.security.ssl.Handshaker.process_record(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:33)
    at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:33)
    at moviescraper.doctord.model.dataitem.Thumb.<init>(Thumb.java:121)
    at moviescraper.doctord.controller.siteparsingprofile.specific.EICBookParsingProfile.scrapePostersAndFanart(EICBookParsingProfile.java:310)
    at moviescraper.doctord.controller.siteparsingprofile.specific.EICBookParsingProfile.scrapePosters(EICBookParsingProfile.java:276)
    at moviescraper.doctord.model.Movie.<init>(Movie.java:135)
    at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:918)
    at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:194)
    at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:1)
    at javax.swing.SwingWorker$1.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at javax.swing.SwingWorker.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
    at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
    at sun.security.validator.Validator.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
    ... 28 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
    at java.security.cert.CertPathBuilder.build(Unknown Source)
    ... 34 more
```

It would be better for security and privacy to implement HTTPS support, I think.

**Comment by DoctorD1501** [comment]
Isn't the problem here that the URL has https in it but the certificate is invalid?

**Comment by MrTimscampi** [comment]
The certificate is valid in Firefox, though.

I think the software needs to verify the certificates, somehow ? I've never done this in Java, but I can look a bit more into it, if need be.

**Comment by Wizell** [comment]
HTTPS urls are working fine. Most of the websites are now using TLS without any trouble.

This seems to be an invalid certificate or a certificate that is not in the java certificate store
