### ISSUE TITLE
nfo files not readable in javmoviescraper

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#163]
Emby is rewriting nfo files that are now unreadable by JMS. So I can't go back and rescrap for new info.

File of nfo after emby.
[Skinny Dipping - 1149247.zip](https://github.com/DoctorD1501/JAVMovieScraper/files/580602/Skinny.Dipping.-.1149247.zip)

My main issue is I just now settled on a folder and nameing scheme. So going back to redo all my older files are impossible.

This is what JMS is saying when i click on the file but nothing loads.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at moviescraper.doctord.model.dataitem.Thumb.<init>(Thumb.java:269)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlActorBean.toActor(KodiXmlActorBean.java:42)
	at moviescraper.doctord.controller.xmlserialization.KodiXmlMovieBean.toMovie(KodiXmlMovieBean.java:147)
	at moviescraper.doctord.controller.SelectFileListAction.readMovieFromNfoFile(SelectFileListAction.java:165)
	at moviescraper.doctord.controller.SelectFileListAction.handleNewSelection(SelectFileListAction.java:104)
	at moviescraper.doctord.controller.SelectFileListAction.valueChanged(SelectFileListAction.java:46)
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source)
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.JList.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DoctorD1501** [comment]
Fixed in latest commit. There's a new dev build on mediafire with the fix.
