### ISSUE TITLE
Fail to open it on Linux

### ISSUE THREAD

**Issue by JulianLai** [DoctorD1501/JAVMovieScraper#170]
Heap size is 807.0M
Heap size good, continue to launch program

(java:9908): Gtk-WARNING **: 無法在 module_path 中找出佈景主題引擎：‘pixmap’，

(java:9908): Gtk-WARNING **: 無法在 module_path 中找出佈景主題引擎：‘pixmap’，

(java:9908): Gtk-WARNING **: 無法在 module_path 中找出佈景主題引擎：‘pixmap’，

(java:9908): Gtk-WARNING **: 無法在 module_path 中找出佈景主題引擎：‘pixmap’，
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at moviescraper.doctord.view.GUIMain.<init>(GUIMain.java:112)
	at moviescraper.doctord.view.GUIMain$1.run(GUIMain.java:126)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by DoctorD1501** [comment]
Check what java version you have. You need Java version 8 from Oracle. Not Java 7 or OpenJDK.

**Comment by JulianLai** [comment]
It works
