### ISSUE TITLE
Not Save Data

### ISSUE THREAD

**Issue by AiWABR** [DoctorD1501/JAVMovieScraper#184]
The application makes the right scrapper, But does not save any information. You can fix this problem

**Comment by brazilcoco** [comment]
same here. v3.4 nothing getting saved. i get this message when trying to save:

**java.io.IOException: (name of video)mp4' could not be created
at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1951)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1911)
at moviescraper.doctord.model.Movie.writeToFile(Movie.java:458)
at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:107)
at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)**

**Comment by brazilcoco** [comment]
> The application makes the right scrapper, But does not save any information. You can fix this problem

no answer in over a year since the topic but i'll try anyway...same issue here. v3.4 nothing getting saved. i get this message when trying to save:

java.io.IOException: (name of video)mp4' could not be created
at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1951)
at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1911)
at moviescraper.doctord.model.Movie.writeToFile(Movie.java:458)
at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:107)
at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
