### ISSUE TITLE
Scrapper for DMM and JAVLibrary broken

### ISSUE THREAD

**Issue by cavalia88** [DoctorD1501/JAVMovieScraper#197]
The scrapper for DMM and JAVLibrary appears to be broken. Would be great if they can be fixed.

Thanks

**Comment by tehwateva** [comment]
Same issue here as well with JavLibrary. Error logs :  

ava.net.MalformedURLException: no protocol: //pics.dmm.co.jp/mono/movie/adult/soe444/soe444pt.jpg
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at moviescraper.doctord.model.dataitem.Thumb.<init>(Thumb.java:250)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.getSearchResults(JavLibraryParsingProfile.java:427)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:865)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:196)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Scraping complete of siteScraper = JavLibrary

**Comment by tehwateva** [comment]
Issue seems to stem from the thumbnail cover itself

If I were to manually provide the URL to scrape using Javlibrary it'll show the title, actress etc except the covers.

**Comment by unknown12345678** [comment]
@Wizell is there anyway you could compile a java build for us?

**Comment by alejo82** [comment]
it would be great it this issue can be fixed as soon as possible.

thank you

**Comment by fidofido300** [comment]
@wizell 
Thanks for your hard work. 
but if search returns more than one result scraper does not work. with the following errors.


Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: protocol = https host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:46)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:33)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:300)
	at moviescraper.doctord.model.dataitem.Thumb.getImageIconThumbImage(Thumb.java:54)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:35)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:1)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at java.awt.Window.dispatchEventImpl(Window.java:2744)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: protocol = https host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:46)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:33)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:300)
	at moviescraper.doctord.model.dataitem.Thumb.getImageIconThumbImage(Thumb.java:54)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:35)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:1)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at java.awt.Window.dispatchEventImpl(Window.java:2744)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: protocol = https host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:46)
	at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:33)
	at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:300)
	at moviescraper.doctord.model.dataitem.Thumb.getImageIconThumbImage(Thumb.java:54)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:35)
	at moviescraper.doctord.view.renderer.SearchResultsRenderer.getListCellRendererComponent(SearchResultsRenderer.java:1)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:578)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at java.awt.Window.dispatchEventImpl(Window.java:2744)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tehwateva** [comment]
I've compiled  a java build that just fixes Javlibrary scrapes, here's the link if anyone wants it : 

https://filejoker.net/olzfzx0ug7u3

**Comment by cavalia88** [comment]
Thanks tehwateva.   Your java build works for Javlibrary scrapes.

Now we just need someone to fix the DMM scrapping.

**Comment by alejo82** [comment]
thank you

**Comment by brunho** [comment]
thanx for build

**Comment by Wizell** [comment]
@fidofido300 I looked for a search that return more than one match on javlibrary and found that "vgd-122" returns 2 matches. Then the parser selects the first item in the result list but i cannot reproduce the same behavior. Could you please provide a search example that generates the error ?

@cavalia88 I just tried again the dmm parser and it seems to works. Could you elaborate on the problem (giving a stack trace or a bogus query) ?

**Comment by unknown12345678** [comment]
@cavalia88 @Wizell 
he could be referring to R18.com (english version of DMM)
doesn't seem to pulling in any genre info

**Comment by fidofido300** [comment]
@Wizell 
Try With 'Scraping Dialogs To show' , 'Select Search Results Manually' enabled
vgd-122 , MIDE-454 doesn't matter both produces same result

**Comment by Wizell** [comment]
@fidofido300 The last commit i made should fix this bug. I only made simple testing but it seems to work.

**Comment by fidofido300** [comment]
Thank You very much this commit fixed the problem con you take a look at issue #181 also.
I think with how the things are progressing you are going to inherit this fabulous program.

**Comment by DarkMask100** [comment]
Appreciate the work @Wizell! 

Seeing how the original author has been MIA for almost a year, maybe you should create an issue to redirect users to your repo to report problems and such?

**Comment by tehwateva** [comment]
I'm not very familiar with how github works, like for every commit you make how do I get the compiled version?

**Comment by Still34** [comment]
@tehwateva This has nothing to do with GitHub. What you're talking about is [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration), which is up to the author. Otherwise, users will have to compile each commit themselves.

**Comment by Wizell** [comment]
@DarkMask100 I'm not familiar with github so i don't know how to do it properly.

**Comment by DarkMask100** [comment]
Just create a new issue and provide the link to your repo so users can report bugs as you're the unofficial active developer now. :) 

I would also edit the README.MD file to reflect this and provide an updated build.

**Comment by Wizell** [comment]
@DarkMask100 Done (ref: #203). Hope it will be clear enough. Also a new release is already posted there.
