### ISSUE TITLE
v0.3.1 doesnt start 

### ISSUE THREAD

**Issue by Nick8005** [DoctorD1501/JAVMovieScraper#208]
Hi everyone, there seem to be issued with getting 0.3.1. to start. I tried on my main system and a second computer,...to no avail, it wont open. No issues with 0.2.27.

**Comment by Wimi2** [comment]
I and another guy had this problem, too. We could both solved it. Perhaps this will help you, too! :).

https://github.com/Wizell/JAVMovieScraper/issues/23

**Comment by Wimi2** [comment]
Let's continue here, because the other repository was only temporary :).

Perhaps it will help to uninstall all Java installations on your computer, then restart, install the new Java (and perhaps restart again). 

As for your error code ("Heap Size is 247.0M. Trying to launch process with heap size of 1024"): I am not sure how to fix this, sorry :(.

**Comment by Nick8005** [comment]
Reinstalling, at least on the win8 machine, didnt make a difference :(

**Comment by Nick8005** [comment]
Any suggestions?

**Comment by Cutters1982** [comment]
Hey Nick

I suggest uninstalling what version of Java that you have and install Java Build 1.8.0_151-b12 instead, that fixed the problem for me :)

**Comment by Wizell** [comment]
@Nick8005 Can you post your PATH system variable and can try to run the software in a cmd console (java -jar JAVMovieScraper.jar in the right folder) and post the output ?

**Comment by Nick8005** [comment]
Hi guys

Thanks for your input. For now I just tried fixing the issue on the one machine, and curiously deleting and reinstalling java did the trick. Even though I had the latest version installed, a simple delete and reinstall (of said version) made the program work again. 

I assume this should also fix the other machine. 

Thanks for the help guys!!

**Comment by Cutters1982** [comment]
I tried uninstalling the java I had installed and installing the most recent java from the website, but that didnt make any difference for me, I had to use the 1.8.0_151-b12 to get the program working.

**Comment by alexjjkuo** [comment]
Got the same problem and found the solution: 
Need to add "-Xmx1G" to use larger heap size.

java -Xmx1G -jar JAVMovieScraper.jar

**Comment by Wizell** [comment]
The application should work fine in java 8 but it seems that some old code is not fully compatible with java 9. So if you encounter trouble with java 9, please try with java 8 while i replace this code (java 8 is still supported upstream untill 2019).

@alexjjkuo Do you still have to do this in 0.3.2 ? the startup process has changed and should take care of this issue.

**Comment by alexjjkuo** [comment]
Hi @Wizell , I am using v0.3.0-idol version, with java 8.161.
If click the application directly, it won't start. If using Command window to call it but without -Xmx1G, it showed following error:
Heap size is 247.0M
Trying to launch process with heap size of 1024

**Comment by Wizell** [comment]
Can you try with version v0.3.3 ?

**Comment by AngryViking32** [comment]
v0.3.3 also doesn't open

**Comment by Wizell** [comment]
Can you try in a command line (cmd on windows) to run java -jar <PATH_TO_JAVMOVIESCRAPER.JAR> and report the output ?

**Comment by AngryViking32** [comment]
This is what I get when I do it with v0.3.3:
CAPSULE EXCEPTION: Illegal char <<> at index 0: <path-to-sdk>/platform-tools (for stack trace, run with -Dcapsule.log=verbose)
Exception in thread "main" java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at Capsule.toFriendlyPath(Capsule.java:3712)
        at Capsule.printHelp(Capsule.java:1185)
        at Capsule.printUsage(Capsule.java:452)
        at Capsule.printError(Capsule.java:448)
        at Capsule.onError0(Capsule.java:5119)
        at Capsule.onError(Capsule.java:5115)
        at Capsule.main0(Capsule.java:398)
        at Capsule.main(Capsule.java:374)

Does this help?

**Comment by Wizell** [comment]
I'm afraid it won't be enough but it already gives a direction. The error is indeed in the capsule loader.

It looks like that the current path of the jar contains invalid character (<).

Some questions comes to mind
Does the path really contains '<' character ?
Are you running the JAR from a network share ?
Can you run java -Dcapsule.log=verbose -jar <PATH_TO_JAVMOVIESCRAPER.JAR>  and report again the output ?

**Comment by AngryViking32** [comment]
Path doesn't contain a '<' (F:\JAVMovieScraper)
Not a network share, its a local disk.
v0.3.4 also doesn't open.

Output from v0.3.4:
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\AngryViking>java -Dcapsule.log=verbose -jar F:\JAVMovieScraper.jar
CAPSULE: Jar: F:\JAVMovieScraper.jar
CAPSULE: Platform: windows
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: moviescraper.doctord.Main
CAPSULE: Launching app moviescraper.doctord.Main
CAPSULE: Starting capsule server.
CAPSULE: Binding capsule server at: 0.0.0.0:56744
CAPSULE: Using JVM: C:\Program Files\Java\jre1.8.0_171
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: C:\Users\AngryViking\AppData\Local\capsule
CAPSULE: Creating temp file/dir C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Locking C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Extracting F:\JAVMovieScraper.jar to app cache directory C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main
CAPSULE: Unlocking C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Cleanup
CAPSULE EXCEPTION: Illegal char <<> at index 0: <path-to-sdk>/platform-tools
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <path-to-sdk>/platform-tools
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at Capsule.path(Capsule.java:3656)
        at Capsule.toPath(Capsule.java:3668)
        at Capsule.getPlatformNativeLibraryPath0(Capsule.java:2431)
        at Capsule.getPlatformNativeLibraryPath(Capsule.java:2424)
        at Capsule.buildNativeLibraryPath(Capsule.java:2406)
        at Capsule.buildSystemProperties(Capsule.java:2368)
        at Capsule.buildSystemProperties(Capsule.java:2349)
        at Capsule.buildJavaProcess(Capsule.java:2217)
        at Capsule.buildProcess0(Capsule.java:1519)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.prelaunch0(Capsule.java:1483)
        at Capsule.prelaunch(Capsule.java:1476)
        at Capsule.prepareForLaunch(Capsule.java:1329)
        at Capsule.launch(Capsule.java:1258)
        at Capsule.main0(Capsule.java:394)
        at Capsule.main(Capsule.java:374)
Exception in thread "main" java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at Capsule.toFriendlyPath(Capsule.java:3712)
        at Capsule.printHelp(Capsule.java:1185)
        at Capsule.printUsage(Capsule.java:452)
        at Capsule.printError(Capsule.java:448)
        at Capsule.onError0(Capsule.java:5119)
        at Capsule.onError(Capsule.java:5115)
        at Capsule.main0(Capsule.java:398)
        at Capsule.main(Capsule.java:374)

Output from v0.3.3:
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\AngryViking>java -Dcapsule.log=verbose -jar F:\JAVMovieScraper.jar
CAPSULE: Jar: F:\JAVMovieScraper.jar
CAPSULE: Platform: windows
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: moviescraper.doctord.Main
CAPSULE: Launching app moviescraper.doctord.Main
CAPSULE: Starting capsule server.
CAPSULE: Binding capsule server at: 0.0.0.0:57398
CAPSULE: Using JVM: C:\Program Files\Java\jre1.8.0_171
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: C:\Users\AngryViking\AppData\Local\capsule
CAPSULE: Creating temp file/dir C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Locking C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Extracting F:\JAVMovieScraper.jar to app cache directory C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main
CAPSULE: Unlocking C:\Users\AngryViking\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Cleanup
CAPSULE EXCEPTION: Illegal char <<> at index 0: <path-to-sdk>/platform-tools
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <path-to-sdk>/platform-tools
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at Capsule.path(Capsule.java:3656)
        at Capsule.toPath(Capsule.java:3668)
        at Capsule.getPlatformNativeLibraryPath0(Capsule.java:2431)
        at Capsule.getPlatformNativeLibraryPath(Capsule.java:2424)
        at Capsule.buildNativeLibraryPath(Capsule.java:2406)
        at Capsule.buildSystemProperties(Capsule.java:2368)
        at Capsule.buildSystemProperties(Capsule.java:2349)
        at Capsule.buildJavaProcess(Capsule.java:2217)
        at Capsule.buildProcess0(Capsule.java:1519)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.prelaunch0(Capsule.java:1483)
        at Capsule.prelaunch(Capsule.java:1476)
        at Capsule.prepareForLaunch(Capsule.java:1329)
        at Capsule.launch(Capsule.java:1258)
        at Capsule.main0(Capsule.java:394)
        at Capsule.main(Capsule.java:374)
Exception in thread "main" java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at sun.nio.fs.WindowsPath.relativize(Unknown Source)
        at Capsule.toFriendlyPath(Capsule.java:3712)
        at Capsule.printHelp(Capsule.java:1185)
        at Capsule.printUsage(Capsule.java:452)
        at Capsule.printError(Capsule.java:448)
        at Capsule.onError0(Capsule.java:5119)
        at Capsule.onError(Capsule.java:5115)
        at Capsule.main0(Capsule.java:398)
        at Capsule.main(Capsule.java:374)

**Comment by Wizell** [comment]
After reading a bit the capsule internal code, i'm wondering if you might not have a wrongly set system variable. Can you check if there is anything wrong in your system variables and most notably the PATH and JAVA_HOME variables ? (if you are unsure if they are valid or not you can post them here)

**Comment by AngryViking32** [comment]
https://i.imgur.com/OOWeyTQ.png

It appears I don't have a JAVA_HOME variable set.
It should be noted that v0.2.27 and earlier work fine

**Comment by Wizell** [comment]
On the screenshot  i cannot see the full value of the path variable in "system variables". It might be a wrong value inside.

The requirement on the proper path value is linked to capsule. Which is removed in master.

**Comment by Wizell** [comment]
version 0.3.5+ doesn't have capsule anymore. Please retry and reopen an issue if the problem still exists
