### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images

### ISSUE THREAD

**Issue by ianmargarone** [DoctorD1501/JAVMovieScraper#212]
Hi,

Whena scraping and it returns the thumbs etc it then fails to add the img and poster. Please see log output below:

java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.datavimg.com/images/stars/120/16923.jpg
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
at moviescraper.doctord.controller.FileDownloaderUtilities.getImageFromUrl(FileDownloaderUtilities.java:41)
at moviescraper.doctord.model.ImageCache.getImageFromCache(ImageCache.java:29)
at moviescraper.doctord.model.dataitem.Thumb.getThumbImage(Thumb.java:282)
at moviescraper.doctord.view.renderer.ActressListRenderer.getImageIconForLabelName(ActressListRenderer.java:136)
at moviescraper.doctord.view.renderer.ActressListRenderer.getListCellRendererComponent(ActressListRenderer.java:60)
at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
at javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
at javax.swing.JComponent.getPreferredSize(Unknown Source)
at javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
at java.awt.Container.layout(Unknown Source)
at java.awt.Container.doLayout(Unknown Source)
at java.awt.Container.validateTree(Unknown Source)
at java.awt.Container.validate(Unknown Source)
at javax.swing.RepaintManager$3.run(Unknown Source)
at javax.swing.RepaintManager$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

It seems that https://i.datavimg.com is longer active. Is there a workaround since it prevents the movie posters from being downloaded as it bails before hand.

Thanks.

**Comment by ianmargarone** [comment]
Bump

**Comment by Cutters1982** [comment]
I guess Data18 caught wind of it and have blocked hotlinking their images...

if you try to open a link you get a forbidden message with "You don't have permission to access /images/stars/120/16923.jpg on this server" for example

**Comment by Wizell** [comment]
@Cutters1982 is right. I need to have a look at how this check is made to find a counter measure

**Comment by Wizell** [comment]
data18 only use referer checking. This can easily be fixed

**Comment by ianmargarone** [comment]
Thanks for the fix. Is there going to be a new release build? I'm not familiar with building gradle projects.

**Comment by ianmargarone** [comment]
bump

**Comment by Wizell** [comment]
Those are part of 0.3.2. If you still encounter problems, please report.

**Comment by Cutters1982** [comment]
@Wizell - there's unfortunately still an issue, even with 0.3.2. I can scrape images for poster & fanart fine but once the info has been pulled the thumbnails for the actor images do not show, and the URL's to those actor images fail to display if I import the nfo files etc into Plex (they just show as grey), which is a bit of a pain :(

For example:-

I scraped the URL http://www.data18.com/content/1148425 via the Data18 Web Content, it allowed me to choose a poster & fanart, and these display fine in the preview

actor thumbs fail to show up in the scraper program
https://i.datavimg.com/images/stars/120/178.jpg
https://i.datavimg.com/images/stars/120/23774.jpg

if I open those links in the same browser that I've loaded the data18 page on, they load, but if I try in another browser I get a 403 forbidden error

Please let me know if you want some more info from me

**Comment by Wizell** [comment]
@Cutters1982 Thank you for the informations. From those i tried a fix and it seems to work. Could you give it a try please ?

**Comment by Cutters1982** [comment]
Thanks Wizell, I'll give it a go, cheers.

Please, when you have a moment, could you take a look at my feature request regarding adding up & down arrows to adjust the order of the cast list? Thanks! :)
