### ISSUE TITLE
cannot save nfo file metadata

### ISSUE THREAD

**Issue by tanyasweet1933** [DoctorD1501/JAVMovieScraper#246]
Not sure whats happened recently i have been getting the following errors, which basically is not allowing the program to create nfo files on disk. This is happening in both GUI and commandline.
I have the latest version of JavMovieScraper and the java version is:

`java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)`

`Java(TM) SE Runtime Environment 1.8.0_181-b13(Oracle Corporation) -- 1.8(Oracle Corporation)
Heap: 989 MB
Free mem: 730 MB
Scraping with scraper = dmm
Filename =  C:\Users\me\Downloads\javscraper\Movies\ADN-165.mp4
Parsing with parsing profile = class moviescraper.doctord.controller.siteparsingprofile.specific.DmmParsingProfile
Scraping this webpage for movie: http://www.dmm.co.jp/mono/dvd/-/detail/=/cid=adn165/?i3_ref=search&i3_ord=1
directors=[Director [toString()=Person [name="Sada Oka Sadao", thumb=null] ," source="DMM.co.jp""]]]
java.io.IOException: Directory 'C:\Users\me\Downloads\javscraper\Movies\ADN-165.mp4' could not be created
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1951)
        at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1911)
        at moviescraper.doctord.model.Movie.writeToFile(Movie.java:458)
        at moviescraper.doctord.Main.writeMovieToFile(Main.java:229)
        at moviescraper.doctord.Main.runScrape(Main.java:195)
        at moviescraper.doctord.Main.main(Main.java:105)
All files written!`

**Comment by assamungus** [comment]
i had the problem of it not writing nfo files and tried the move to new folder option and then scraped the file again and it would write the nfo file

**Comment by tanyasweet1933** [comment]
thanks...Not sure what id id because i did a lot of things :) but i think uninstalling the java and installing an older version helped but I cant be too sure about that. anyway its working now.
