### ISSUE TITLE
empty infromation

### ISSUE THREAD

**Issue by brazilcoco** [DoctorD1501/JAVMovieScraper#251]
was working for awhile. now when use everything is empty. no info  or images are showing after clicking the scrape button

**Comment by brazilcoco** [comment]
log file info from a video:

java.net.UnknownHostException: www.squareplus.co.jp
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.SquarePlusParsingProfile.getSearchResults(SquarePlusParsingProfile.java:262)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.javbus.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavBusParsingProfile.getSearchResults(JavBusParsingProfile.java:345)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.r18.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.R18ParsingProfile.searchResultOnR18(R18ParsingProfile.java:399)
	at moviescraper.doctord.controller.siteparsingprofile.specific.R18ParsingProfile.getSearchResults(R18ParsingProfile.java:433)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.dmm.co.jp
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.DmmParsingProfile.getSearchResults(DmmParsingProfile.java:669)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.javdog.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavZooParsingProfile.getSearchResults(JavZooParsingProfile.java:338)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.javlibrary.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.getSearchResults(JavLibraryParsingProfile.java:377)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.net.UnknownHostException: www.actionjav.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.ActionJavParsingProfile.getSearchResults(ActionJavParsingProfile.java:315)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Scraping complete of siteScraper = SquarePlus
Scraping complete of siteScraper = JavBus
Scraping complete of siteScraper = R18.com
Scraping complete of siteScraper = DMM.co.jp
Scraping complete of siteScraper = JavZoo
Scraping complete of siteScraper = JavLibrary
Scraping complete of siteScraper = ActionJav
currentItemSource = JavLibrary with disabled = false
currentItemSource = Default Data Item Source with disabled = false
M:\games\VR videos\asian\black\BLACK?BLACK\BKBK008\BKBK008.mp4
java.net.UnknownHostException: www.javlibrary.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:439)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.getSearchResults(JavLibraryParsingProfile.java:377)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by brazilcoco** [comment]
and IF i happen to get teh info i cant write it out. get this message instead:


java.io.IOException: (name of video)mp4' could not be created
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1951)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1911)
	at moviescraper.doctord.model.Movie.writeToFile(Movie.java:458)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:107)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by brazilcoco** [comment]
no helP?
