### ISSUE TITLE
not writing file data

### ISSUE THREAD

**Issue by assamungus** [DoctorD1501/JAVMovieScraper#255]
program worked a few times now just errors...

java.io.IOException: Directory 'C:\Users\xxx\Documents\xxx\MUM-191.AVI.mp4' could not be created
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1951)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1911)
	at moviescraper.doctord.model.Movie.writeToFile(Movie.java:458)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:107)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by assamungus** [comment]
fixed..needed to move into new folder before writing data
