### ISSUE TITLE
CAPSULE EXCEPTION: Illegal char <"> at index 0: "C:\Program Files\ffmpeg-win64\bin"

### ISSUE THREAD

**Issue by 98745632** [DoctorD1501/JAVMovieScraper#262]
Cant even run the thing, running` java -jar JAVMovieScraper.jar` shows the title as error before exiting

Whole log ahead
```
java -Dcapsule.log=verbose -jar JAVMovieScraper.jar
CAPSULE: Jar: C:\Users\<NAME>\Desktop\JAVMovieScraper.jar
CAPSULE: Platform: windows
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: moviescraper.doctord.Main
CAPSULE: Launching app moviescraper.doctord.Main
CAPSULE: Starting capsule server.
CAPSULE: Binding capsule server at: 0.0.0.0:5938
CAPSULE: Using JVM: C:\Program Files (x86)\Java\jre1.8.0_191
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: C:\Users\<NAME>\AppData\Local\capsule
CAPSULE: Creating temp file/dir C:\Users\<NAME>\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Locking C:\Users\<NAME>\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Extracting C:\Users\<NAME>\Desktop\JAVMovieScraper.jar to app cache directory C:\Users\<NAME>\AppData\Local\capsule\apps\moviescraper.doctord.Main
CAPSULE: Unlocking C:\Users\<NAME>\AppData\Local\capsule\apps\moviescraper.doctord.Main\.lock
CAPSULE: Cleanup
CAPSULE EXCEPTION: Illegal char <"> at index 0: "C:\Program Files\ffmpeg-win64\bin"
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\ffmpeg-win64\bin"
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at Capsule.path(Capsule.java:3656)
        at Capsule.toPath(Capsule.java:3668)
        at Capsule.getPlatformNativeLibraryPath0(Capsule.java:2431)
        at Capsule.getPlatformNativeLibraryPath(Capsule.java:2424)
        at Capsule.buildNativeLibraryPath(Capsule.java:2406)
        at Capsule.buildSystemProperties(Capsule.java:2368)
        at Capsule.buildSystemProperties(Capsule.java:2349)
        at Capsule.buildJavaProcess(Capsule.java:2217)
        at Capsule.buildProcess0(Capsule.java:1519)
        at Capsule.buildProcess(Capsule.java:1510)
        at Capsule.prelaunch0(Capsule.java:1483)
        at Capsule.prelaunch(Capsule.java:1476)
        at Capsule.prepareForLaunch(Capsule.java:1329)
        at Capsule.launch(Capsule.java:1258)
        at Capsule.main0(Capsule.java:394)
        at Capsule.main(Capsule.java:374)
USAGE: java <options> -jar JAVMovieScraper.jar

Actions:
  capsule.version - Prints the capsule and application versions.
  capsule.modes - Prints all available capsule modes.
  capsule.jvms - Prints a list of all JVM installations found.
  capsule.help - Prints this help message.

Options:
  capsule.mode=<value> - Picks the capsule mode to run.
  capsule.reset - Resets the capsule cache before launching. The capsule to be re-extracted (if applicable), and other possibly cached files will be recreated.
  capsule.log=<value> (default: quiet) - Picks a log level. Must be one of none, quiet, verbose, or debug.
  capsule.java.home=<value> - Sets the location of the Java home (JVM installation directory) to use; If 'current' forces the use of the JVM that launched the capsule.
  capsule.java.cmd=<value> - Sets the path to the Java executable to use.
  capsule.jvm.args=<value> - Sets additional JVM arguments to use when running the application.
```
ffmpeg is properly installed/configured

```
ffmpeg -version
ffmpeg version N-91655-g7e0df5910e Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20180813
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil      56. 19.100 / 56. 19.100
libavcodec     58. 24.101 / 58. 24.101
libavformat    58. 17.103 / 58. 17.103
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 26.100 /  7. 26.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100
```

**Comment by Wizell** [comment]
Seeing the lack of upstream activity (nothing since 2107/01), capsule is being removed in the next version.

**Comment by joshuachong97** [comment]
Same issue here, any fix?
