### ISSUE TITLE
Change : to - in file names

### ISSUE THREAD

**Issue by mjsmjs** [DoctorD1501/JAVMovieScraper#289]
**Describe the bug**
When I bulk scrap and : is in the file name saving and moving files fails.

this is what it says
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:443)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:424)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:178)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:167)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavZooParsingProfile.getSearchResults(JavZooParsingProfile.java:338)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:769)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:180)
	at moviescraper.doctord.controller.amalgamation.ScrapeAmalgamatedMovieWorker$1.doInBackground(ScrapeAmalgamatedMovieWorker.java:169)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wizell** [comment]
The error present in the report is that your internet connection had troubles.

Are you sure this is always reproduced with the same set of files ?

Is it working when you have only one file with ':' or '*' ?

**Comment by mjsmjs** [comment]
Gui Initialized
Movie Size: 1
Writing this movie to file: Title [title="Extreme Molestation: test" source="Default Data Item Source"]
Was file, new name = H:\Movies\Japanese\Sorted\Apache\2017\2017-09-01 - Extreme Molestation\2017\2017-09-01 - Extreme Molestation: test\Extreme Molestation test.mp4
New Filename : H:\Movies\Japanese\Sorted\Apache\2017\2017-09-01 - Extreme Molestation\2017\2017-09-01 - Extreme Molestation: test\Extreme Molestation test.mp4
java.io.FileNotFoundException: Destination directory 'H:\Movies\Japanese\Sorted\Apache\2017\2017-09-01 - Extreme Molestation\2017\2017-09-01 - Extreme Molestation: test' does not exist [createDestDir=true]
	at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2865)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:86)
	at moviescraper.doctord.controller.WriteFileDataAction$1.doInBackground(WriteFileDataAction.java:36)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Must have grab the wrong error. Here is a test. When I scrape then click write file data this is what happens.

**Comment by TheWhiteDoll** [comment]
I've experienced the same issue. I tend to include the movie title in the folder name, and if it contains any characters not allowed by Windows ( : " / \ | ? * ) it fails because it can't create the directory. Which makes sense.

I've been manually deleting the characters before writing/moving to a folder, but it'd be nice to have it auto-replace them with a dash or underscore, or some other acceptable character.

On a side note, Windows will allow the Japanese unicode version of those characters (？ etc), if that's useful to anyone.

**Comment by Wizell** [comment]
It should be filtered against the description: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming_conventions
