### ISSUE TITLE
v0.3.7 Crashes on start

### ISSUE THREAD

**Issue by JCzepiel** [DoctorD1501/JAVMovieScraper#299]
When double clicking the .jar file it crashes right away.

Here is the stack trace I see:

C:\Users\C\Downloads\JAVMovieScraper-0.3.7>java -jar JAVMovieScraper-v0.3
.7.jar
Java(TM) SE Runtime Environment 1.8.0_221-b11(Oracle Corporation) -- 1.8(Oracle
Corporation)
Heap: 3 GB
Free mem: 241 MB
Initializing default jav preferences
Sep 05, 2019 9:52:22 PM moviescraper.doctord.scraper.DitzyHeadlessBrowser <init>

INFO: Build browser with U: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.
0) Gecko/20100101 Firefox/59.0
java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at moviescraper.doctord.scraper.DitzyHeadlessBrowser.configure(DitzyHead
lessBrowser.java:35)
        at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibrar
yParsingProfile.browserConfigure(JavLibraryParsingProfile.java:102)
        at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibrar
yParsingProfile.<init>(JavLibraryParsingProfile.java:93)
        at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingP
references.initializeJAVCensoredGroupDefaultPreferences(AllAmalgamationOrderingP
references.java:129)
        at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingP
references.initializeDefaultPreferences(AllAmalgamationOrderingPreferences.java:
103)
        at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingP
references.initializeValuesFromPreferenceFile(AllAmalgamationOrderingPreferences
.java:69)
        at moviescraper.doctord.view.GUIMain.reinitializeAmalgamationPreferences
FromFile(GUIMain.java:157)
        at moviescraper.doctord.view.GUIMain.initialize(GUIMain.java:169)
        at moviescraper.doctord.view.GUIMain.<init>(GUIMain.java:142)
        at moviescraper.doctord.view.GUIMain$1.run(GUIMain.java:126)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by godcong** [comment]
same error with me:
```
Java(TM) SE Runtime Environment 1.8.0_221-b11(Oracle Corporation) -- 1.8(Oracle Corporation)                            Heap: 7 GB                                                                                                              Free mem: 485 MB                                                                                                        Initializing default jav preferences                                                                                    九月 11, 2019 5:19:01 下午 moviescraper.doctord.scraper.DitzyHeadlessBrowser <init>                                     信息: Build browser with U: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0          java.lang.NullPointerException                                                                                                  at java.io.File.<init>(Unknown Source)                                                                                  at moviescraper.doctord.scraper.DitzyHeadlessBrowser.configure(DitzyHeadlessBrowser.java:35)                            at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.browserConfigure(JavLibraryParsingProfile.java:102)                                                                                                     at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.<init>(JavLibraryParsingProfile.java:93)                                                                                                                at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeJAVCensoredGroupDefaultPreferences(AllAmalgamationOrderingPreferences.java:129)                                                                    at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeDefaultPreferences(AllAmalgamationOrderingPreferences.java:103)
        at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeValuesFromPreferenceFile(AllAmalgamationOrderingPreferences.java:69)
        at moviescraper.doctord.view.GUIMain.reinitializeAmalgamationPreferencesFromFile(GUIMain.java:157)
        at moviescraper.doctord.view.GUIMain.initialize(GUIMain.java:169)
        at moviescraper.doctord.view.GUIMain.<init>(GUIMain.java:142)
        at moviescraper.doctord.view.GUIMain$1.run(GUIMain.java:126)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by jl0476** [comment]
Same error with me

```java
Java(TM) SE Runtime Environment 1.8.0_131-b11(Oracle Corporation) -- 1.8(Oracle Corporation)
Heap: 3 GB
Free mem: 241 MB
Initializing default jav preferences
十月 31, 2019 1:49:55 下午 moviescraper.doctord.scraper.DitzyHeadlessBrowser <init>
信息: Build browser with U: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at moviescraper.doctord.scraper.DitzyHeadlessBrowser.configure(DitzyHeadlessBrowser.java:35)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.browserConfigure(JavLibraryParsingProfile.java:102)
	at moviescraper.doctord.controller.siteparsingprofile.specific.JavLibraryParsingProfile.<init>(JavLibraryParsingProfile.java:93)
	at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeJAVCensoredGroupDefaultPreferences(AllAmalgamationOrderingPreferences.java:129)
	at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeDefaultPreferences(AllAmalgamationOrderingPreferences.java:103)
	at moviescraper.doctord.controller.amalgamation.AllAmalgamationOrderingPreferences.initializeValuesFromPreferenceFile(AllAmalgamationOrderingPreferences.java:69)
	at moviescraper.doctord.view.GUIMain.reinitializeAmalgamationPreferencesFromFile(GUIMain.java:157)
	at moviescraper.doctord.view.GUIMain.initialize(GUIMain.java:169)
	at moviescraper.doctord.view.GUIMain.<init>(GUIMain.java:142)
	at moviescraper.doctord.view.GUIMain$1.run(GUIMain.java:126)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by NJCCJohnWason** [comment]
![图片](https://user-images.githubusercontent.com/17756284/68236729-adae2700-0040-11ea-999a-699c7717e997.png)
same as me ...

**Comment by domxch** [comment]
This seems to be due to this:-

	private MoviescraperPreferences() {

		//initialize default values that must exist in the settings file

	}

**Comment by kaosnews** [comment]
Quick solution: Download an older version, run it - it will create AmalgamationSettings.json and then you can run the latest version

**Comment by NJCCJohnWason** [comment]
> 
> 
> Quick solution: Download an older version, run it - it will create AmalgamationSettings.json and then you can run the latest version

It's ok! When I put the new .jar file in the path of  older jar file, thanks a lot!

**Comment by NJCCJohnWason** [comment]
> 
> 
> This seems to be due to this:-
> 
> ```
> private MoviescraperPreferences() {
> 
> 	//initialize default values that must exist in the settings file
> 
> }
> ```

it means the must  exist an older json file, right?

**Comment by thecat18** [comment]
I also have this issue, running the other version worked but not the new one, I can't understand the last few messages, I run the .jar file from a regular downloads folder should i put it somewhere else?

**Comment by NJCCJohnWason** [comment]
> I also have this issue, running the other version worked but not the new one, I can't understand the last few messages, I run the .jar file from a regular downloads folder should i put it somewhere else?

just put new version exe to old version folder

**Comment by thecat18** [comment]
Ok I will try that later tonight.

**Comment by thecat18** [comment]
ok I extracted the .jar .exe file over the old version folders, how do I open the software, I usually right click on that jar exe file & open with java using windows 10.

**Comment by NJCCJohnWason** [comment]
> 
> 
> ok I extracted the .jar .exe file over the old version folders, how do I open the software, I usually right click on that jar exe file & open with java using windows 10.

👌

**Comment by thecat18** [comment]
Am I doing something wrong

**Comment by thecat18** [comment]
Ok I figured it out after taking a couple weeks off from this.  Thanks for helping.

**Comment by mesol86** [comment]
I still cannot use GUI, getting this error. Can anybody explain which Java version did you install? I downgraded to Java 8, build 111, still no luck. But I'm able to scape using command prompt.

Do we need to download both the source files (files and folders) together with .jar file?

And what .exe did someone mentioned above? Java.exe in "bin" folder of Java installation path?

**Comment by mesol86** [comment]
I able to run by create .bat file.

Create "run.bat" by right click and new file. Select Notepad. Rename the file to "run.bat".

Edit the file and add this line: "java -jar JAVMovieScraper.jar". Save the file and run by double clicking the "run.bat"
