### ISSUE TITLE
it can't work

### ISSUE THREAD

**Issue by whatrye** [DoctorD1501/JAVMovieScraper#315]
**Describe the bug**
\>java -jar JAVMovieScraper-v0.3.7.jar
Java(TM) SE Runtime Environment 13.0.2+8(Oracle Corporation) -- 13(Oracle Corporation)
Heap: 1 GB
Free mem: 91 MB
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at moviescraper.doctord.view.GUIMain.<init>(GUIMain.java:112)
        at moviescraper.doctord.view.GUIMain$1.run(GUIMain.java:126)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 15 more

**Give an example**
An example of scrape that did not work

**Comment by whatrye** [comment]
how to fix it?

**Comment by YoYspoon** [comment]
Same issue here with 0.3.7, but 0.3.6 works

**Comment by lbbboy** [comment]
me to

**Comment by bg2908** [comment]
Use Oracle JDK8 make it work for me
 
Here is my version from the terminal:
 Java(TM) SE Runtime Environment 1.8.0_251-b08(Oracle Corporation) -- 1.8(Oracle Corporation)

**Comment by Wizell** [comment]
This application uses javaFX, which is a standalone SDK since java 11.

You can find more informations here: https://openjfx.io/
