### ISSUE TITLE
Error while scraping(Caribbeancom)

### ISSUE THREAD

**Issue by NapInFever** [DoctorD1501/JAVMovieScraper#67]
Encounter this error. 
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Must supply a valid URL
	at org.jsoup.helper.Validate.notEmpty(Validate.java:102)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:57)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:27)
	at org.jsoup.Jsoup.connect(Jsoup.java:73)
	at moviescraper.doctord.controller.SpecificScraperAction.downloadDocument(SpecificScraperAction.java:195)
	at moviescraper.doctord.controller.SpecificScraperAction.scrape(SpecificScraperAction.java:158)
	at moviescraper.doctord.controller.ScrapeSpecificAction.actionPerformed(ScrapeSpecificAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Tried this file:070514-637

**Comment by DoctorD1501** [comment]
Are you still getting this error for this file? I just tried this now and it worked, so perhaps the site was having some temporary problems on their end.

**Comment by NapInFever** [comment]
It is working now. Thanks
