### ISSUE TITLE
Unable to scrape individual scene, from movie

### ISSUE THREAD

**Issue by d2dyno** [DoctorD1501/JAVMovieScraper#81]
When trying to scrape a scene, from a movie (let's say scene 3, of movie xyz), scraper finds it, but fails to actually collect Metadata. The log shows an error in red text (which I will post later if necessary).

**Comment by d2dyno** [comment]
Log error always looks like this:

Exception in thread "Thread-7" java.lang.NullPointerException
	at moviescraper.doctord.SiteParsingProfile.Data18WebContentParsingProfile.scrapeYear(Data18WebContentParsingProfile.java:97)
	at moviescraper.doctord.model.Movie.<init>(Movie.java:133)
	at moviescraper.doctord.model.Movie.scrapeMovie(Movie.java:900)
	at moviescraper.doctord.controller.ScrapeMovieAction$3.run(ScrapeMovieAction.java:615)

**Comment by DoctorD1501** [comment]
Hey d2dyno,

I've just uploaded a fix for this in the newest development build. You can get the development build from the mediafire link on the project page or wait until I release the next official release to get the fix.

Thanks.
